env:
  browser: true
  es6: true
extends:
  - airbnb
  - prettier
  - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-props-no-spreading: off
settings:
    import/resolver:
        alias:
            map:
              - ["@Components", "./src/components"]
              - ["@Modules", "./src/modules"]
              - ["@Content", "./src/content"]
              - ["@Assets", "./src/assets"]
              - ["@Spanish", "./src/apps/Spanish"]