env:
  browser: true
  es6: true
  jest/globals: true
parser: "@typescript-eslint/parser"
extends:
  - prettier
  - plugin:@typescript-eslint/recommended
  - next/core-web-vitals
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - jest
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx", 'tsx'] }]
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-props-no-spreading: off
settings:
    import/resolver:
        alias:
            map:
              - ["@App", "./src/app"]
              - ["@Public", "./public"]
              - ["@Components", "./src/components"]
              - ["@Modules", "./src/modules"]
              - ["@Styles", "./src/styles"]
              - ["@Content", "./src/content"]
              - ["@Apps", "./src/apps"]